language: go
go:
  - 1.16.x

env:
  global:
    - GO111MODULE=auto

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0

script:
  - make
